// Generated by js_of_ocaml 3.8.0
(function(c){"use strict";var
bM="%Li",bN=" : flags Open_text and Open_binary are not compatible",cm="Invalid_argument",a4=1255,b3=255,b4=0x800,O=0xffff,a3="jsError",N=0x8000,cl="%ni",cc=12520,b2=256,b1="End_of_file",b0="Failure",cb="infinity",W=0xff,aw=1000,bL="Stack_overflow",f="",a7="^",E="0",bK=-97,am=0x3f,bJ="Not_found",a2=0xf,ay=128,bY=-48,bZ=0xdc00,cj="Sys_blocked_io",ck="fd ",ca="Match_failure",B=248,bI="static/",q="camlinternalFormat.ml",bX="Division_by_zero",a6=252,ci=1027,bW="Sys_error",al=".",ak="+",b$=0xf0,ch="%u",bV="%d",bH=1026,b_="%li",bU="buffer.ml",b9=-32,a_=127,ax=1024,T=" ",L=0x80,a9="e",bG="Undefined_recursive_module",bS=120,bT=103,cg=" : flags Open_rdonly and Open_wronly are not compatible",cf="([^/]*)",bR=512,ae="-",a5="nan",bQ=0x7ff0,b8=0xe0,ce=" : file already exists",b7=0xdfff,V=0xffffff,a1="compare: functional value",b6="Assert_failure",U="/",bP="0x",bF="%i",cd="Out_of_memory",aL=254,a8="index out of bounds",bO=100,b5=250,aM="_bigarr02";function
bl(c,b,a){var
d=String.fromCharCode;if(b==0&&a<=4096&&a==c.length)return d.apply(null,c);var
e=f;for(;0<a;b+=ax,a-=ax)e+=d.apply(null,c.slice(b,b+Math.min(a,ax)));return e}function
aN(b){if(c.Uint8Array)var
d=new(c.Uint8Array)(b.l);else
var
d=new
Array(b.l);var
f=b.c,e=f.length,a=0;for(;a<e;a++)d[a]=f.charCodeAt(a);for(e=b.l;a<e;a++)d[a]=0;b.c=d;b.t=4;return d}function
af(d,e,b,f,c){if(c==0)return 0;if(f==0&&(c>=b.l||b.t==2&&c>=b.c.length)){b.c=d.t==4?bl(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else
if(b.t==2&&f==b.c.length){b.c+=d.t==4?bl(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else{if(b.t!=4)aN(b);var
g=d.c,h=b.c;if(d.t==4)if(f<=e)for(var
a=0;a<c;a++)h[f+a]=g[e+a];else
for(var
a=c-1;a>=0;a--)h[f+a]=g[e+a];else{var
i=Math.min(c,g.length-e);for(var
a=0;a<i;a++)h[f+a]=g.charCodeAt(e+a);for(;a<c;a++)h[f+a]=0}}return 0}function
ao(a){return a}function
ag(a,b,c,d,e){af(ao(a),b,c,d,e);return 0}function
fx(b,a){throw[0,b,a]}function
ar(b,a){if(b==0)return f;if(a.repeat)return a.repeat(b);var
d=f,c=0;for(;;){if(b&1)d+=a;b>>=1;if(b==0)return d;a+=a;c++;if(c==9)a.slice(0,1)}}function
aO(a){if(a.t==2)a.c+=ar(a.l-a.c.length,"\0");else
a.c=bl(a.c,0,a.c.length);a.t=0}function
cN(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>a_)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
bn(e){for(var
k=f,c=f,h,g,i,a,b=0,j=e.length;b<j;b++){g=e.charCodeAt(b);if(g<L){for(var
d=b+1;d<j&&(g=e.charCodeAt(d))<L;d++);if(d-b>bR){c.substr(0,1);k+=c;c=f;k+=e.slice(b,d)}else
c+=e.slice(b,d);if(d==j)break;b=d}a=1;if(++b<j&&((i=e.charCodeAt(b))&-64)==ay){h=i+(g<<6);if(g<b8){a=h-0x3080;if(a<L)a=1}else{a=2;if(++b<j&&((i=e.charCodeAt(b))&-64)==ay){h=i+(h<<6);if(g<b$){a=h-0xe2080;if(a<b4||a>=0xd7ff&&a<0xe000)a=2}else{a=3;if(++b<j&&((i=e.charCodeAt(b))&-64)==ay&&g<0xf5){a=i-0x3c82080+(h<<6);if(a<0x10000||a>0x10ffff)a=3}}}}}if(a<4){b-=a;c+="\ufffd"}else
if(a>O)c+=String.fromCharCode(0xd7c0+(a>>10),bZ+(a&0x3FF));else
c+=String.fromCharCode(a);if(c.length>ax){c.substr(0,1);k+=c;c=f}}return k+c}function
X(c,a,b){this.t=c;this.c=a;this.l=b}X.prototype.toString=function(){switch(this.t){case
9:return this.c;default:aO(this);case
0:if(cN(this.c)){this.t=9;return this.c}this.t=8;case
8:return this.c}};X.prototype.toUtf16=function(){var
a=this.toString();if(this.t==9)return a;return bn(a)};X.prototype.slice=function(){var
a=this.t==4?this.c.slice():this.c;return new
X(this.t,a,this.l)};function
cw(a){return new
X(0,a,a.length)}function
a(a){return cw(a)}function
bk(c,b){fx(c,a(b))}var
n=[0];function
r(a){bk(n.Invalid_argument,a)}function
cu(){r(a8)}function
m(a,c,b){b&=W;if(a.t!=4){if(c==a.c.length){a.c+=String.fromCharCode(b);if(c+1==a.l)a.t=0;return 0}aN(a)}a.c[c]=b;return 0}function
ah(b,a,c){if(a>>>0>=b.l)cu();return m(b,a,c)}function
az(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
aa(c,a){if(c.fun)return aa(c.fun,a);if(typeof
c!=="function")return c;var
b=c.length|0;if(b===0)return c.apply(null,a);var
e=a.length|0,d=b-e|0;if(d==0)return c.apply(null,a);else
if(d<0)return aa(c.apply(null,a.slice(0,b)),a.slice(b));else
return function(){var
e=arguments.length==0?1:arguments.length,d=new
Array(a.length+e);for(var
b=0;b<a.length;b++)d[b]=a[b];for(var
b=0;b<arguments.length;b++)d[a.length+b]=arguments[b];return aa(c,d)}}function
e4(a){if(isFinite(a)){if(Math.abs(a)>=2.2250738585072014e-308)return 0;if(a!=0)return 1;return 2}return isNaN(a)?4:3}function
u(a){if(a<0)r("Bytes.create");return new
X(a?2:9,f,a)}function
e5(a,c,b,d){if(b>0)if(c==0&&(b>=a.l||a.t==2&&b>=a.c.length))if(d==0){a.c=f;a.t=2}else{a.c=ar(b,String.fromCharCode(d));a.t=b==a.l?0:2}else{if(a.t!=4)aN(a);for(b+=c;c<b;c++)a.c[c]=d}return 0}function
ab(a){if((a.t&6)!=0)aO(a);return a.c}function
bj(d){d=ab(d);var
e=d.length;if(e>31)r("format_int: format too long");var
a={justify:ak,signstyle:ae,filler:T,alternate:false,base:0,signedconv:false,width:0,uppercase:false,sign:1,prec:-1,conv:"f"};for(var
c=0;c<e;c++){var
b=d.charAt(c);switch(b){case"-":a.justify=ae;break;case"+":case" ":a.signstyle=b;break;case"0":a.filler=E;break;case"#":a.alternate=true;break;case"1":case"2":case"3":case"4":case"5":case"6":case"7":case"8":case"9":a.width=0;while(b=d.charCodeAt(c)-48,b>=0&&b<=9){a.width=a.width*10+b;c++}c--;break;case".":a.prec=0;c++;while(b=d.charCodeAt(c)-48,b>=0&&b<=9){a.prec=a.prec*10+b;c++}c--;case"d":case"i":a.signedconv=true;case"u":a.base=10;break;case"x":a.base=16;break;case"X":a.base=16;a.uppercase=true;break;case"o":a.base=8;break;case"e":case"f":case"g":a.signedconv=true;a.conv=b;break;case"E":case"F":case"G":a.signedconv=true;a.uppercase=true;a.conv=b.toLowerCase();break}}return a}function
bc(b,g){if(b.uppercase)g=g.toUpperCase();var
e=g.length;if(b.signedconv&&(b.sign<0||b.signstyle!=ae))e++;if(b.alternate){if(b.base==8)e+=1;if(b.base==16)e+=2}var
c=f;if(b.justify==ak&&b.filler==T)for(var
d=e;d<b.width;d++)c+=T;if(b.signedconv)if(b.sign<0)c+=ae;else
if(b.signstyle!=ae)c+=b.signstyle;if(b.alternate&&b.base==8)c+=E;if(b.alternate&&b.base==16)c+=bP;if(b.justify==ak&&b.filler==E)for(var
d=e;d<b.width;d++)c+=E;c+=g;if(b.justify==ae)for(var
d=e;d<b.width;d++)c+=T;return a(c)}function
cC(i,c){function
j(a,b){if(Math.abs(a)<1.0)return a.toFixed(b);else{var
c=parseInt(a.toString().split(ak)[1]);if(c>20){c-=20;a/=Math.pow(10,c);a+=new
Array(c+1).join(E);if(b>0)a=a+al+new
Array(b+1).join(E);return a}else
return a.toFixed(b)}}var
a,e=bj(i),d=e.prec<0?6:e.prec;if(c<0||c==0&&1/c==-Infinity){e.sign=-1;c=-c}if(isNaN(c)){a=a5;e.filler=T}else
if(!isFinite(c)){a="inf";e.filler=T}else
switch(e.conv){case"e":var
a=c.toExponential(d),b=a.length;if(a.charAt(b-3)==a9)a=a.slice(0,b-1)+E+a.slice(b-1);break;case"f":a=j(c,d);break;case"g":d=d?d:1;a=c.toExponential(d-1);var
h=a.indexOf(a9),g=+a.slice(h+1);if(g<-4||c>=1e21||c.toFixed(0).length>d){var
b=h-1;while(a.charAt(b)==E)b--;if(a.charAt(b)==al)b--;a=a.slice(0,b+1)+a.slice(h);b=a.length;if(a.charAt(b-3)==a9)a=a.slice(0,b-1)+E+a.slice(b-1);break}else{var
f=d;if(g<0){f-=g+1;a=c.toFixed(f)}else
while(a=c.toFixed(f),a.length>d+1)f--;if(f){var
b=a.length-1;while(a.charAt(b)==E)b--;if(a.charAt(b)==al)b--;a=a.slice(0,b+1)}}break}return bc(e,a)}function
aP(e,c){if(ab(e)==bV)return a(f+c);var
b=bj(e);if(c<0)if(b.signedconv){b.sign=-1;c=-c}else
c>>>=0;var
d=c.toString(b.base);if(b.prec>=0){b.filler=T;var
g=b.prec-d.length;if(g>0)d=ar(g,E)+d}return bc(b,d)}var
fu=0;function
aB(){return fu++}function
ap(a){bk(n.Failure,a)}function
cF(a){return a.toUtf16()}if(c.process&&c.process.cwd)var
aA=c.process.cwd().replace(/\\/g,U);else
var
aA="/static";if(aA.slice(-1)!==U)aA+=U;function
fo(a){a=cF(a);if(a.charCodeAt(0)!=47)a=aA+a;var
d=a.split(U),b=[];for(var
c=0;c<d.length;c++)switch(d[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(f);break;default:b.push(d[c]);break}b.orig=a;return b}function
aS(a){return a
instanceof
X}function
bi(a){return aS(a)}function
e2(a){return new
X(4,a,a.length)}function
fC(e){for(var
g=f,b=g,a,i,c=0,h=e.length;c<h;c++){a=e.charCodeAt(c);if(a<L){for(var
d=c+1;d<h&&(a=e.charCodeAt(d))<L;d++);if(d-c>bR){b.substr(0,1);g+=b;b=f;g+=e.slice(c,d)}else
b+=e.slice(c,d);if(d==h)break;c=d}if(a<b4){b+=String.fromCharCode(0xc0|a>>6);b+=String.fromCharCode(L|a&am)}else
if(a<0xd800||a>=b7)b+=String.fromCharCode(b8|a>>12,L|a>>6&am,L|a&am);else
if(a>=0xdbff||c+1==h||(i=e.charCodeAt(c+1))<bZ||i>b7)b+="\xef\xbf\xbd";else{c++;a=(a<<10)+i-0x35fdc00;b+=String.fromCharCode(b$|a>>18,L|a>>12&am,L|a>>6&am,L|a&am)}if(b.length>ax){b.substr(0,1);g+=b;b=f}}return g+b}function
e3(a){var
b=9;if(!cN(a))b=8,a=fC(a);return new
X(b,a,a.length)}function
ac(a){return e3(a)}function
g(a){bk(n.Sys_error,a)}function
fw(a){a=ab(a);g(a+": No such file or directory")}function
e1(b,a){if(a>>>0>=b.l)cu();return az(b,a)}function
J(a){return a.l}function
cn(){}function
t(a){this.data=a}t.prototype=new
cn();t.prototype.truncate=function(a){var
b=this.data;this.data=u(a|0);af(b,0,this.data,0,a)};t.prototype.length=function(){return J(this.data)};t.prototype.write=function(b,d,g,a){var
c=this.length();if(b+a>=c){var
e=u(b+a),f=this.data;this.data=e;af(f,0,this.data,0,c)}ag(d,g,this.data,b,a);return 0};t.prototype.read=function(c,a,d,b){var
e=this.length();af(this.data,c,a,d,b);return 0};t.prototype.read_one=function(a){return e1(this.data,a)};t.prototype.close=function(){};t.prototype.constructor=t;function
I(b,a){this.content={};this.root=b;this.lookupFun=a}I.prototype.nm=function(a){return this.root+a};I.prototype.lookup=function(b){if(!this.content[b]&&this.lookupFun){var
c=this.lookupFun(a(this.root),a(b));if(c!==0)this.content[b]=new
t(ao(c[1]))}};I.prototype.exists=function(a){if(a==f)return 1;var
c=a+U,d=new
RegExp(a7+c);for(var
b
in
this.content)if(b.match(d))return 1;this.lookup(a);return this.content[a]?1:0};I.prototype.readdir=function(c){var
g=c==f?f:c+U,h=new
RegExp(a7+g+cf),d={},b=[];for(var
e
in
this.content){var
a=e.match(h);if(a&&!d[a[1]]){d[a[1]]=true;b.push(a[1])}}return b};I.prototype.is_dir=function(a){var
d=a==f?f:a+U,e=new
RegExp(a7+d+cf),g=[];for(var
c
in
this.content){var
b=c.match(e);if(b)return 1}return 0};I.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};I.prototype.open=function(a,b){if(b.rdonly&&b.wronly)g(this.nm(a)+cg);if(b.text&&b.binary)g(this.nm(a)+bN);this.lookup(a);if(this.content[a]){if(this.is_dir(a))g(this.nm(a)+" : is a directory");if(b.create&&b.excl)g(this.nm(a)+ce);var
c=this.content[a];if(b.truncate)c.truncate();return c}else
if(b.create){this.content[a]=new
t(u(0));return this.content[a]}else
fw(this.nm(a))};I.prototype.register=function(b,a){if(this.content[b])g(this.nm(b)+ce);if(aS(a))this.content[b]=new
t(a);if(bi(a))this.content[b]=new
t(ao(a));else
if(a
instanceof
Array)this.content[b]=new
t(e2(a));else
if(typeof
a==="string")this.content[b]=new
t(cw(a));else
if(a.toString){var
c=ao(ac(a.toString()));this.content[b]=new
t(c)}else
g(this.nm(b)+" : registering file with invalid content type")};I.prototype.constructor=I;function
y(a){return J(a)}function
aF(b,a){return az(b,a)}function
eY(d){var
c=y(d),b=new
Array(c),a=0;for(;a<c;a++)b[a]=aF(d,a);return b}function
eX(a){if(a.t!=4)aN(a);return a.c}function
Q(a){this.fs=require("fs");this.fd=a}Q.prototype=new
cn();Q.prototype.truncate=function(a){try{this.fs.ftruncateSync(this.fd,a|0)}catch(a){g(a.toString())}};Q.prototype.length=function(){try{return this.fs.fstatSync(this.fd).size}catch(a){g(a.toString())}};Q.prototype.write=function(h,b,d,f){var
a=eY(b);if(!(a
instanceof
c.Uint8Array))a=new(c.Uint8Array)(a);var
e=c.Buffer.from(a);try{this.fs.writeSync(this.fd,e,d,f,h)}catch(a){g(a.toString())}return 0};Q.prototype.read=function(i,e,d,h){var
a=eX(e);if(!(a
instanceof
c.Uint8Array))a=new(c.Uint8Array)(a);var
f=c.Buffer.from(a);try{this.fs.readSync(this.fd,f,d,h,i)}catch(a){g(a.toString())}for(var
b=0;b<h;b++)ah(e,d+b,f[d+b]);return 0};Q.prototype.read_one=function(d){var
b=new(c.Uint8Array)(1),a=c.Buffer.from(b);try{this.fs.readSync(this.fd,a,0,1,d)}catch(a){g(a.toString())}return a[0]};Q.prototype.close=function(){try{this.fs.closeSync(this.fd)}catch(a){g(a.toString())}};Q.prototype.constructor=Q;function
P(a){this.fs=require("fs");this.root=a}P.prototype.nm=function(a){return this.root+a};P.prototype.exists=function(a){try{return this.fs.existsSync(this.nm(a))?1:0}catch(a){g(a.toString())}};P.prototype.readdir=function(a){try{return this.fs.readdirSync(this.nm(a))}catch(a){g(a.toString())}};P.prototype.is_dir=function(a){try{return this.fs.statSync(this.nm(a)).isDirectory()?1:0}catch(a){g(a.toString())}};P.prototype.unlink=function(a){try{var
b=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a))}catch(a){g(a.toString())}return b};P.prototype.open=function(f,c){var
a=require("constants"),b=0;for(var
e
in
c)switch(e){case"rdonly":b|=a.O_RDONLY;break;case"wronly":b|=a.O_WRONLY;break;case"append":b|=a.O_WRONLY|a.O_APPEND;break;case"create":b|=a.O_CREAT;break;case"truncate":b|=a.O_TRUNC;break;case"excl":b|=a.O_EXCL;break;case"binary":b|=a.O_BINARY;break;case"text":b|=a.O_TEXT;break;case"nonblock":b|=a.O_NONBLOCK;break}try{var
d=this.fs.openSync(this.nm(f),b);return new
Q(d)}catch(a){g(a.toString())}};P.prototype.rename=function(b,a){try{this.fs.renameSync(this.nm(b),this.nm(a))}catch(a){g(a.toString())}};P.prototype.constructor=P;var
aq=aA.match(/[^\/]*\//)[0];function
fE(){return typeof
c.process!=="undefined"&&typeof
c.process.versions!=="undefined"&&typeof
c.process.versions.node!=="undefined"&&c.process.platform!=="browser"}var
aG=[];if(fE())aG.push({path:aq,device:new
P(aq)});else
aG.push({path:aq,device:new
I(aq)});aG.push({path:aq+bI,device:new
I(aq+bI)});function
cO(b){var
f=fo(b),b=f.join(U),e=b+U,c;for(var
d=0;d<aG.length;d++){var
a=aG[d];if(e.search(a.path)==0&&(!c||c.path.length<a.path.length))c={path:a.path,device:a.device,rest:b.substring(a.path.length,b.length)}}return c}function
cA(c,b){var
c=typeof
c=="string"?a(c):c,b=typeof
b=="string"?a(b):b,d=cO(c);if(!d.device.register)ap("cannot register file");d.device.register(d.rest,b);return 0}function
e6(){var
b=c.caml_fs_tmp;if(b)for(var
a=0;a<b.length;a++)cA(b[a].name,b[a].content);c.caml_create_file=cA;c.caml_fs_tmp=[];return 0}var
fI=Math.log2&&Math.log2(1.1235582092889474E+307)==1020;function
fH(a){if(fI)return Math.floor(Math.log2(a));var
b=0;if(a==0)return-Infinity;if(a>=1)while(a>=2){a/=2;b++}else
while(a<1){a*=2;b--}return b}function
bd(d){var
a=new(c.Float32Array)(1);a[0]=d;var
b=new(c.Int32Array)(a.buffer);return b[0]|0}var
cE=Math.pow(2,-24);function
fv(a){throw a}function
cK(){fv(n.Division_by_zero)}function
b(b,c,a){this.lo=b&V;this.mi=c&V;this.hi=a&O}b.prototype.caml_custom="_j";b.prototype.copy=function(){return new
b(this.lo,this.mi,this.hi)};b.prototype.ucompare=function(a){if(this.hi>a.hi)return 1;if(this.hi<a.hi)return-1;if(this.mi>a.mi)return 1;if(this.mi<a.mi)return-1;if(this.lo>a.lo)return 1;if(this.lo<a.lo)return-1;return 0};b.prototype.compare=function(a){var
b=this.hi<<16,c=a.hi<<16;if(b>c)return 1;if(b<c)return-1;if(this.mi>a.mi)return 1;if(this.mi<a.mi)return-1;if(this.lo>a.lo)return 1;if(this.lo<a.lo)return-1;return 0};b.prototype.neg=function(){var
a=-this.lo,c=-this.mi+(a>>24),d=-this.hi+(c>>24);return new
b(a,c,d)};b.prototype.add=function(a){var
c=this.lo+a.lo,d=this.mi+a.mi+(c>>24),e=this.hi+a.hi+(d>>24);return new
b(c,d,e)};b.prototype.sub=function(a){var
c=this.lo-a.lo,d=this.mi-a.mi+(c>>24),e=this.hi-a.hi+(d>>24);return new
b(c,d,e)};b.prototype.mul=function(a){var
c=this.lo*a.lo,d=(c*cE|0)+this.mi*a.lo+this.lo*a.mi,e=(d*cE|0)+this.hi*a.lo+this.mi*a.mi+this.lo*a.hi;return new
b(c,d,e)};b.prototype.isZero=function(){return(this.lo|this.mi|this.hi)==0};b.prototype.isNeg=function(){return this.hi<<16<0};b.prototype.and=function(a){return new
b(this.lo&a.lo,this.mi&a.mi,this.hi&a.hi)};b.prototype.or=function(a){return new
b(this.lo|a.lo,this.mi|a.mi,this.hi|a.hi)};b.prototype.xor=function(a){return new
b(this.lo^a.lo,this.mi^a.mi,this.hi^a.hi)};b.prototype.shift_left=function(a){a=a&63;if(a==0)return this;if(a<24)return new
b(this.lo<<a,this.mi<<a|this.lo>>24-a,this.hi<<a|this.mi>>24-a);if(a<48)return new
b(0,this.lo<<a-24,this.mi<<a-24|this.lo>>48-a);return new
b(0,0,this.lo<<a-48)};b.prototype.shift_right_unsigned=function(a){a=a&63;if(a==0)return this;if(a<24)return new
b(this.lo>>a|this.mi<<24-a,this.mi>>a|this.hi<<24-a,this.hi>>a);if(a<48)return new
b(this.mi>>a-24|this.hi<<48-a,this.hi>>a-24,0);return new
b(this.hi>>a-48,0,0)};b.prototype.shift_right=function(a){a=a&63;if(a==0)return this;var
d=this.hi<<16>>16;if(a<24)return new
b(this.lo>>a|this.mi<<24-a,this.mi>>a|d<<24-a,this.hi<<16>>a>>>16);var
c=this.hi<<16>>31;if(a<48)return new
b(this.mi>>a-24|this.hi<<48-a,this.hi<<16>>a-24>>16,c&O);return new
b(this.hi<<16>>a-32,c,c)};b.prototype.lsl1=function(){this.hi=this.hi<<1|this.mi>>23;this.mi=(this.mi<<1|this.lo>>23)&V;this.lo=this.lo<<1&V};b.prototype.lsr1=function(){this.lo=(this.lo>>>1|this.mi<<23)&V;this.mi=(this.mi>>>1|this.hi<<23)&V;this.hi=this.hi>>>1};b.prototype.udivmod=function(f){var
d=0,c=this.copy(),a=f.copy(),e=new
b(0,0,0);while(c.ucompare(a)>0){d++;a.lsl1()}while(d>=0){d--;e.lsl1();if(c.ucompare(a)>=0){e.lo++;c=c.sub(a)}a.lsr1()}return{quotient:e,modulus:c}};b.prototype.div=function(a){var
b=this;if(a.isZero())cK();var
d=b.hi^a.hi;if(b.hi&N)b=b.neg();if(a.hi&N)a=a.neg();var
c=b.udivmod(a).quotient;if(d&N)c=c.neg();return c};b.prototype.mod=function(b){var
a=this;if(b.isZero())cK();var
d=a.hi;if(a.hi&N)a=a.neg();if(b.hi&N)b=b.neg();var
c=a.udivmod(b).modulus;if(d&N)c=c.neg();return c};b.prototype.toInt=function(){return this.lo|this.mi<<24};b.prototype.toFloat=function(){return(this.hi<<16)*Math.pow(2,32)+this.mi*Math.pow(2,24)+this.lo};b.prototype.toArray=function(){return[this.hi>>8,this.hi&W,this.mi>>16,this.mi>>8&W,this.mi&W,this.lo>>16,this.lo>>8&W,this.lo&W]};b.prototype.lo32=function(){return this.lo|(this.mi&W)<<24};b.prototype.hi32=function(){return this.mi>>>8&O|this.hi<<16};function
aR(c,d,a){return new
b(c,d,a)}function
aQ(a){if(!isFinite(a)){if(isNaN(a))return aR(1,0,bQ);return a>0?aR(0,0,bQ):aR(0,0,0xfff0)}var
f=a==0&&1/a==-Infinity?N:a>=0?0:N;if(f)a=-a;var
b=fH(a)+1023;if(b<=0){b=0;a/=Math.pow(2,-bH)}else{a/=Math.pow(2,b-ci);if(a<16){a*=2;b-=1}if(b==0)a/=2}var
d=Math.pow(2,24),c=a|0;a=(a-c)*d;var
e=a|0;a=(a-e)*d;var
g=a|0;c=c&a2|f|b<<4;return aR(g,e,c)}function
aD(a){return a.toArray()}function
ct(c,b,g){c.write(32,b.dims.length);c.write(32,b.kind|b.layout<<8);if(b.caml_custom==aM)for(var
a=0;a<b.dims.length;a++)if(b.dims[a]<O)c.write(16,b.dims[a]);else{c.write(16,O);c.write(32,0);c.write(32,b.dims[a])}else
for(var
a=0;a<b.dims.length;a++)c.write(32,b.dims[a]);switch(b.kind){case
2:case
3:case
12:for(var
a=0;a<b.data.length;a++)c.write(8,b.data[a]);break;case
4:case
5:for(var
a=0;a<b.data.length;a++)c.write(16,b.data[a]);break;case
6:for(var
a=0;a<b.data.length;a++)c.write(32,b.data[a]);break;case
8:case
9:c.write(8,0);for(var
a=0;a<b.data.length;a++)c.write(32,b.data[a]);break;case
7:for(var
a=0;a<b.data.length/2;a++){var
e=aD(b.get(a));for(var
d=0;d<8;d++)c.write(8,e[d])}break;case
1:for(var
a=0;a<b.data.length;a++){var
e=aD(aQ(b.get(a)));for(var
d=0;d<8;d++)c.write(8,e[d])}break;case
0:for(var
a=0;a<b.data.length;a++){var
e=bd(b.get(a));c.write(32,e)}break;case
10:for(var
a=0;a<b.data.length/2;a++){var
d=b.get(a);c.write(32,bd(d[1]));c.write(32,bd(d[2]))}break;case
11:for(var
a=0;a<b.data.length/2;a++){var
f=b.get(a),e=aD(aQ(f[1]));for(var
d=0;d<8;d++)c.write(8,e[d]);var
e=aD(aQ(f[2]));for(var
d=0;d<8;d++)c.write(8,e[d])}break}g[0]=(4+b.dims.length)*4;g[1]=(4+b.dims.length)*8}function
cr(a){switch(a){case
7:case
10:case
11:return 2;default:return 1}}function
eZ(d,f){var
b=c,a;switch(d){case
0:a=b.Float32Array;break;case
1:a=b.Float64Array;break;case
2:a=b.Int8Array;break;case
3:a=b.Uint8Array;break;case
4:a=b.Int16Array;break;case
5:a=b.Uint16Array;break;case
6:a=b.Int32Array;break;case
7:a=b.Int32Array;break;case
8:a=b.Int32Array;break;case
9:a=b.Int32Array;break;case
10:a=b.Float32Array;break;case
11:a=b.Float64Array;break;case
12:a=b.Uint8Array;break}if(!a)r("Bigarray.create: unsupported kind");var
e=new
a(f*cr(d));return e}function
be(d){var
a=new(c.Int32Array)(1);a[0]=d;var
b=new(c.Float32Array)(a.buffer);return b[0]}function
aC(a){return new
b(a[7]<<0|a[6]<<8|a[5]<<16,a[4]<<0|a[3]<<8|a[2]<<16,a[1]<<0|a[0]<<8)}function
bf(d){var
f=d.lo,g=d.mi,b=d.hi,c=(b&0x7fff)>>4;if(c==2047)return(f|g|b&a2)==0?b&N?-Infinity:Infinity:NaN;var
e=Math.pow(2,-24),a=(f*e+g)*e+(b&a2);if(c>0){a+=16;a*=Math.pow(2,c-ci)}else
a*=Math.pow(2,-bH);if(b&N)a=-a;return a}function
ba(b){var
d=b.length,c=1;for(var
a=0;a<d;a++){if(b[a]<0)r("Bigarray.create: negative dimension");c=c*b[a]}return c}function
fa(c,a){return new
b(c&V,c>>>24&W|(a&O)<<8,a>>>16&O)}function
bg(a){return a.hi32()}function
bh(a){return a.lo32()}function
a$(){r(a8)}var
e0=aM;function
$(c,d,b,a){this.kind=c;this.layout=d;this.dims=b;this.data=a}$.prototype.caml_custom=e0;$.prototype.offset=function(b){var
c=0;if(typeof
b==="number")b=[b];if(!(b
instanceof
Array))r("bigarray.js: invalid offset");if(this.dims.length!=b.length)r("Bigarray.get/set: bad number of dimensions");if(this.layout==0)for(var
a=0;a<this.dims.length;a++){if(b[a]<0||b[a]>=this.dims[a])a$();c=c*this.dims[a]+b[a]}else
for(var
a=this.dims.length-1;a>=0;a--){if(b[a]<1||b[a]>this.dims[a])a$();c=c*this.dims[a]+(b[a]-1)}return c};$.prototype.get=function(a){switch(this.kind){case
7:var
d=this.data[a*2+0],b=this.data[a*2+1];return fa(d,b);case
10:case
11:var
e=this.data[a*2+0],c=this.data[a*2+1];return[aL,e,c];default:return this.data[a]}};$.prototype.set=function(a,b){switch(this.kind){case
7:this.data[a*2+0]=bh(b);this.data[a*2+1]=bg(b);break;case
10:case
11:this.data[a*2+0]=b[1];this.data[a*2+1]=b[2];break;default:this.data[a]=b;break}return 0};$.prototype.fill=function(b){switch(this.kind){case
7:var
c=bh(b),e=bg(b);if(c==e)this.data.fill(c);else
for(var
a=0;a<this.data.length;a++)this.data[a]=a%2==0?c:e;break;case
10:case
11:var
d=b[1],f=b[2];if(d==f)this.data.fill(d);else
for(var
a=0;a<this.data.length;a++)this.data[a]=a%2==0?d:f;break;default:this.data.fill(b);break}};$.prototype.compare=function(b,g){if(this.layout!=b.layout||this.kind!=b.kind){var
e=this.kind|this.layout<<8,f=b.kind|b.layout<<8;return f-e}if(this.dims.length!=b.dims.length)return b.dims.length-this.dims.length;for(var
a=0;a<this.dims.length;a++)if(this.dims[a]!=b.dims[a])return this.dims[a]<b.dims[a]?-1:1;switch(this.kind){case
0:case
1:case
10:case
11:var
c,d;for(var
a=0;a<this.data.length;a++){c=this.data[a];d=b.data[a];if(c<d)return-1;if(c>d)return 1;if(c!=d){if(!g)return NaN;if(c==c)return 1;if(d==d)return-1}}break;case
7:for(var
a=0;a<this.data.length;a+=2){if(this.data[a+1]<b.data[a+1])return-1;if(this.data[a+1]>b.data[a+1])return 1;if(this.data[a]>>>0<b.data[a]>>>0)return-1;if(this.data[a]>>>0>b.data[a]>>>0)return 1}break;case
2:case
3:case
4:case
5:case
6:case
8:case
9:case
12:for(var
a=0;a<this.data.length;a++){if(this.data[a]<b.data[a])return-1;if(this.data[a]>b.data[a])return 1}break}return 0};function
an(c,d,b,a){this.kind=c;this.layout=d;this.dims=b;this.data=a}an.prototype=new
$();an.prototype.offset=function(a){if(typeof
a!=="number")if(a
instanceof
Array&&a.length==1)a=a[0];else
r("Ml_Bigarray_c_1_1.offset");if(a<0||a>=this.dims[0])a$();return a};an.prototype.get=function(a){return this.data[a]};an.prototype.set=function(a,b){this.data[a]=b;return 0};an.prototype.fill=function(a){this.data.fill(a);return 0};function
cp(c,d,a,b){var
e=cr(c);if(ba(a)*e!=b.length)r("length doesn't match dims");if(d==0&&a.length==1&&e==1)return new
an(c,d,a,b);return new
$(c,d,a,b)}function
cq(b,v,r){var
i=b.read32s();if(i<0||i>16)ap("input_value: wrong number of bigarray dimensions");var
p=b.read32s(),j=p&W,o=p>>8&1,h=[];if(r==aM)for(var
a=0;a<i;a++){var
n=b.read16u();if(n==O){var
t=b.read32u(),u=b.read32u();if(t!=0)ap("input_value: bigarray dimension overflow in 32bit");n=u}h.push(n)}else
for(var
a=0;a<i;a++)h.push(b.read32u());var
d=ba(h),f=eZ(j,d),g=cp(j,o,h,f);switch(j){case
2:for(var
a=0;a<d;a++)f[a]=b.read8s();break;case
3:case
12:for(var
a=0;a<d;a++)f[a]=b.read8u();break;case
4:for(var
a=0;a<d;a++)f[a]=b.read16s();break;case
5:for(var
a=0;a<d;a++)f[a]=b.read16u();break;case
6:for(var
a=0;a<d;a++)f[a]=b.read32s();break;case
8:case
9:var
s=b.read8u();if(s)ap("input_value: cannot read bigarray with 64-bit OCaml ints");for(var
a=0;a<d;a++)f[a]=b.read32s();break;case
7:var
e=new
Array(8);for(var
a=0;a<d;a++){for(var
c=0;c<8;c++)e[c]=b.read8u();var
q=aC(e);g.set(a,q)}break;case
1:var
e=new
Array(8);for(var
a=0;a<d;a++){for(var
c=0;c<8;c++)e[c]=b.read8u();var
k=bf(aC(e));g.set(a,k)}break;case
0:for(var
a=0;a<d;a++){var
k=be(b.read32s());g.set(a,k)}break;case
10:for(var
a=0;a<d;a++){var
m=be(b.read32s()),l=be(b.read32s());g.set(a,[aL,m,l])}break;case
11:var
e=new
Array(8);for(var
a=0;a<d;a++){for(var
c=0;c<8;c++)e[c]=b.read8u();var
m=bf(aC(e));for(var
c=0;c<8;c++)e[c]=b.read8u();var
l=bf(aC(e));g.set(a,[aL,m,l])}break}v[0]=(4+i)*4;return cp(j,o,h,f)}function
co(a,b,c){return a.compare(b,c)}function
cH(a,b){return Math.imul(a,b)}function
Y(b,a){a=cH(a,0xcc9e2d51|0);a=a<<15|a>>>32-15;a=cH(a,0x1b873593);b^=a;b=b<<13|b>>>32-13;return(b+(b<<2)|0)+(0xe6546b64|0)|0}function
e8(a,b){a=Y(a,bh(b));a=Y(a,bg(b));return a}function
cD(a,b){return e8(a,aQ(b))}function
cs(c){var
b=ba(c.dims),d=0;switch(c.kind){case
2:case
3:case
12:if(b>b2)b=b2;var
e=0,a=0;for(a=0;a+4<=c.data.length;a+=4){e=c.data[a+0]|c.data[a+1]<<8|c.data[a+2]<<16|c.data[a+3]<<24;d=Y(d,e)}e=0;switch(b&3){case
3:e=c.data[a+2]<<16;case
2:e|=c.data[a+1]<<8;case
1:e|=c.data[a+0];d=Y(d,e)}break;case
4:case
5:if(b>ay)b=ay;var
e=0,a=0;for(a=0;a+2<=c.data.length;a+=2){e=c.data[a+0]|c.data[a+1]<<16;d=Y(d,e)}if((b&1)!=0)d=Y(d,c.data[a]);break;case
6:if(b>64)b=64;for(var
a=0;a<b;a++)d=Y(d,c.data[a]);break;case
8:case
9:if(b>64)b=64;for(var
a=0;a<b;a++)d=Y(d,c.data[a]);break;case
7:if(b>32)b=32;b*=2;for(var
a=0;a<b;a++)d=Y(d,c.data[a]);break;case
10:b*=2;case
0:if(b>64)b=64;for(var
a=0;a<b;a++)d=cD(d,c.data[a]);break;case
11:b*=2;case
1:if(b>32)b=32;for(var
a=0;a<b;a++)d=cD(d,c.data[a]);break}return d}function
e_(a,b){b[0]=4;return a.read32s()}function
fs(a,b){switch(a.read8u()){case
1:b[0]=4;return a.read32s();case
2:ap("input_value: native integer value too large");default:ap("input_value: ill-formed native integer")}}function
fj(c,d){var
b=new
Array(8);for(var
a=0;a<8;a++)b[a]=c.read8u();d[0]=8;return aC(b)}function
ff(e,d,b){var
c=aD(d);for(var
a=0;a<8;a++)e.write(8,c[a]);b[0]=8;b[1]=8}function
e$(a,b,c){return a.compare(b)}function
fc(a){return a.lo32()^a.hi32()}var
cB={"_j":{deserialize:fj,serialize:ff,fixed_length:8,compare:e$,hash:fc},"_i":{deserialize:e_,fixed_length:4},"_n":{deserialize:fs,fixed_length:4},"_bigarray":{deserialize:function(a,b){return cq(a,b,"_bigarray")},serialize:ct,compare:co,hash:cs},"_bigarr02":{deserialize:function(a,b){return cq(a,b,aM)},serialize:ct,compare:co,hash:cs}};function
bb(a){return cB[a.caml_custom]&&cB[a.caml_custom].compare}function
cy(f,c,d,e){var
b=bb(c);if(b){var
a=d>0?b(c,f,e):b(f,c,e);if(e&&a!=a)return d;if(+a!=+a)return+a;if((a|0)!=0)return a|0}return d}function
cz(a){if(typeof
a==="number")return aw;else
if(aS(a))return a6;else
if(bi(a))return 1252;else
if(a
instanceof
Array&&a[0]===a[0]>>>0&&a[0]<=b3){var
b=a[0]|0;return b==aL?0:b}else
if(a
instanceof
String)return cc;else
if(typeof
a=="string")return cc;else
if(a
instanceof
Number)return aw;else
if(a&&a.caml_custom)return a4;else
if(a&&a.compare)return 1256;else
if(typeof
a=="function")return 1247;else
if(typeof
a=="symbol")return 1251;return 1001}function
fk(a,b){if(a<b)return-1;if(a==b)return 0;return 1}function
cv(a,b){a.t&6&&aO(a);b.t&6&&aO(b);return a.c<b.c?-1:a.c>b.c?1:0}function
fJ(a,b){return cv(a,b)}function
cx(a,b,d){var
e=[];for(;;){if(!(d&&a===b)){var
f=cz(a);if(f==b5){a=a[1];continue}var
g=cz(b);if(g==b5){b=b[1];continue}if(f!==g){if(f==aw){if(g==a4)return cy(a,b,-1,d);return-1}if(g==aw){if(f==a4)return cy(b,a,1,d);return 1}return f<g?-1:1}switch(f){case
247:r(a1);break;case
248:var
c=fk(a[2],b[2]);if(c!=0)return c|0;break;case
249:r(a1);break;case
250:r("equal: got Forward_tag, should not happen");break;case
251:r("equal: abstract value");break;case
252:if(a!==b){var
c=cv(a,b);if(c!=0)return c|0}break;case
253:r("equal: got Double_tag, should not happen");break;case
254:r("equal: got Double_array_tag, should not happen");break;case
255:r("equal: got Custom_tag, should not happen");break;case
1247:r(a1);break;case
1255:var
i=bb(a);if(i!=bb(b))return a.caml_custom<b.caml_custom?-1:1;if(!i)r("compare: abstract value");var
c=i(a,b,d);if(c!=c)return d?-1:c;if(c!==(c|0))return-1;if(c!=0)return c|0;break;case
1256:var
c=a.compare(b,d);if(c!=c)return d?-1:c;if(c!==(c|0))return-1;if(c!=0)return c|0;break;case
1000:a=+a;b=+b;if(a<b)return-1;if(a>b)return 1;if(a!=b){if(!d)return NaN;if(a==a)return 1;if(b==b)return-1}break;case
1001:if(a<b)return-1;if(a>b)return 1;if(a!=b){if(!d)return NaN;if(a==a)return 1;if(b==b)return-1}break;case
1251:if(a!==b){if(!d)return NaN;return 1}break;case
1252:var
a=ab(a),b=ab(b);if(a!==b){if(a<b)return-1;if(a>b)return 1}break;case
12520:var
a=a.toString(),b=b.toString();if(a!==b){if(a<b)return-1;if(a>b)return 1}break;case
246:case
254:default:if(a.length!=b.length)return a.length<b.length?-1:1;if(a.length>1)e.push(a,b,1);break}}if(e.length==0)return 0;var
h=e.pop();b=e.pop();a=e.pop();if(h+1<a.length)e.push(a,b,h+1);a=a[h];b=b[h]}}function
e7(a,b){return+(cx(a,b,false)>=0)}function
e9(a,c,l){if(!isFinite(a)){if(isNaN(a))return ac(a5);return ac(a>0?cb:"-infinity")}var
j=a==0&&1/a==-Infinity?1:a>=0?0:1;if(j)a=-a;var
d=0;if(a==0);else
if(a<1)while(a<1&&d>-1022){a*=2;d--}else
while(a>=2){a/=2;d++}var
k=d<0?f:ak,e=f;if(j)e=ae;else
switch(l){case
43:e=ak;break;case
32:e=T;break;default:break}if(c>=0&&c<13){var
h=Math.pow(2,c*4);a=Math.round(a*h)/h}var
b=a.toString(16);if(c>=0){var
i=b.indexOf(al);if(i<0)b+=al+ar(c,E);else{var
g=i+1+c;if(b.length<g)b+=ar(g-b.length,E);else
b=b.substr(0,g)}}return ac(e+bP+b+"p"+k+d.toString(10))}function
fe(a){return+a.isZero()}function
fh(a){return new
b(a&V,a>>24&V,a>>31&O)}function
fi(a){return a.toInt()}function
fd(a){return+a.isNeg()}function
fg(a){return a.neg()}function
fb(h,c){var
a=bj(h);if(a.signedconv&&fd(c)){a.sign=-1;c=fg(c)}var
b=f,i=fh(a.base),g="0123456789abcdef";do{var
e=c.udivmod(i);c=e.quotient;b=g.charAt(fi(e.modulus))+b}while(!fe(c));if(a.prec>=0){a.filler=T;var
d=a.prec-b.length;if(d>0)b=ar(d,E)+b}return bc(a,b)}function
fl(){return typeof
module!=="undefined"&&module&&module.exports?module.exports:c}function
fm(d){return function(){var
b=arguments.length;if(b>0){var
c=new
Array(b);for(var
a=0;a<b;a++)c[a]=arguments[a];return aa(d,c)}else
return aa(d,[undefined])}}function
fn(d){return function(){var
c=arguments.length,b=new
Array(c+1);b[0]=this;for(var
a=0;a<c;a++)b[a+1]=arguments[a];return aa(d,b)}}var
Z=new
Array();function
fp(c){var
a=Z[c];if(!a.opened)g("Cannot flush a closed channel");if(!a.buffer||a.buffer==f)return 0;if(a.fd&&n.fds[a.fd]&&n.fds[a.fd].output){var
b=n.fds[a.fd].output;switch(b.length){case
2:b(c,a.buffer);break;default:b(a.buffer)}}a.buffer=f;return 0}function
cM(e,f){var
b=Z[e],d=a(f),c=y(d);b.file.write(b.offset,d,0,c);b.offset+=c;return 0}function
fF(a){var
a=bn(a),b=c;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stderr.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
d=b.console;d&&d.error&&d.error(a)}}function
fG(a){var
a=bn(a),b=c;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stdout.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
d=b.console;d&&d.log&&d.log(a)}}function
aT(c,e,d,a){if(n.fds===undefined)n.fds=new
Array();a=a?a:{};var
b={};b.file=d;b.offset=a.append?d.length():0;b.flags=a;b.output=e;n.fds[c]=b;if(!n.fd_last_idx||c>n.fd_last_idx)n.fd_last_idx=c;return c}function
fK(c,b,h){var
a={};while(b){switch(b[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}b=b[2]}if(a.rdonly&&a.wronly)g(ab(c)+cg);if(a.text&&a.binary)g(ab(c)+bN);var
d=cO(c),e=d.device.open(d.rest,a),f=n.fd_last_idx?n.fd_last_idx:0;return aT(f+1,cM,e,a)}aT(0,cM,new
t(u(0)));aT(1,fG,new
t(u(0)));aT(2,fF,new
t(u(0)));function
fq(c){var
b=n.fds[c];if(b.flags.wronly)g(ck+c+" is writeonly");var
a={file:b.file,offset:b.offset,fd:c,opened:true,out:false,refill:null};Z[a.fd]=a;return a.fd}function
cG(c){var
b=n.fds[c];if(b.flags.rdonly)g(ck+c+" is readonly");var
a={file:b.file,offset:b.offset,fd:c,opened:true,out:true,buffer:f};Z[a.fd]=a;return a.fd}function
fr(){var
b=0;for(var
a=0;a<Z.length;a++)if(Z[a]&&Z[a].opened&&Z[a].out)b=[0,Z[a].fd,b];return b}function
aE(a,b){return+(cx(a,b,false)!=0)}function
ft(a){if(a
instanceof
Array&&a[0]==a[0]>>>0)return a[0];else
if(aS(a))return a6;else
if(bi(a))return a6;else
if(a
instanceof
Function||typeof
a=="function")return 247;else
if(a&&a.caml_custom)return b3;else
return aw}function
K(b,d,a){if(a&&c.toplevelReloc)b=c.toplevelReloc(a);n[b+1]=d;if(a)n[a]=d}var
cJ={};function
fy(a,b){cJ[ab(a)]=b;return 0}function
fz(){r(a8)}function
H(b,a){if(a>>>0>=y(b))fz();return aF(b,a)}function
F(a){return a}function
fA(){return[0,a("js_of_ocaml")]}function
fB(){return 0x7FFFFFFF/4|0}function
bm(a){var
b=1;while(a&&a.joo_tramp){a=a.joo_tramp.apply(null,a.joo_args);b++}return a}function
v(b,a){return{joo_tramp:b,joo_args:a}}function
cL(a){return a}function
cI(a){return cJ[a]}function
fD(a){if(a
instanceof
Array)return a;if(c.RangeError&&a
instanceof
c.RangeError&&a.message&&a.message.match(/maximum call stack/i))return cL(n.Stack_overflow);if(c.InternalError&&a
instanceof
c.InternalError&&a.message&&a.message.match(/too much recursion/i))return cL(n.Stack_overflow);if(a
instanceof
c.Error&&cI(a3))return[0,cI(a3),a];return[0,n.Failure,ac(String(a))]}function
d(a,b){return a.length==1?a(b):aa(a,[b])}function
M(a,b,c){return a.length==2?a(b,c):aa(a,[b,c])}e6();var
bq=[B,a(bW),-2],bp=[B,a(b0),-3],bo=[B,a(cm),-4],l=[B,a(b6),-11],bz=[0,bT];K(11,[B,a(bG),-12],bG);K(10,l,b6);K(9,[B,a(cj),-10],cj);K(8,[B,a(bL),-9],bL);K(7,[B,a(ca),-8],ca);K(6,[B,a(bJ),-7],bJ);K(5,[B,a(bX),-6],bX);K(4,[B,a(b1),-5],b1);K(3,bo,cm);K(2,bp,b0);K(1,bq,bW);K(0,[B,a(cd),-1],cd);var
cQ=a("true"),cR=a("false"),cT=a("\\\\"),cU=a("\\'"),cV=a("\\b"),cW=a("\\t"),cX=a("\\n"),cY=a("\\r"),c1=a("String.blit / Bytes.blit_string"),c0=a("Bytes.blit"),cZ=a("String.sub / Bytes.sub"),c4=a("Buffer.add: cannot grow buffer"),c3=[0,a(bU),93,2],c2=[0,a(bU),94,2],db=a("%c"),dc=a("%s"),dd=a(bF),de=a(b_),df=a(cl),dg=a(bM),dh=a("%f"),di=a("%B"),dj=a("%{"),dk=a("%}"),dl=a("%("),dm=a("%)"),dn=a("%a"),dp=a("%t"),dq=a("%?"),dr=a("%r"),ds=a("%_r"),dt=[0,a(q),850,23],dE=[0,a(q),814,21],dw=[0,a(q),815,21],dF=[0,a(q),818,21],dx=[0,a(q),819,21],dG=[0,a(q),822,19],dy=[0,a(q),823,19],dH=[0,a(q),826,22],dz=[0,a(q),827,22],dI=[0,a(q),831,30],dA=[0,a(q),832,30],dC=[0,a(q),836,26],du=[0,a(q),837,26],dD=[0,a(q),846,28],dv=[0,a(q),847,28],dB=[0,a(q),851,23],eK=a(ch),eI=[0,a(q),1558,4],eJ=a("Printf: bad conversion %["),eL=[0,a(q),1626,39],eM=[0,a(q),1649,31],eN=[0,a(q),1650,31],eO=a("Printf: bad conversion %_"),eP=a("@{"),eQ=a("@["),eG=a(a5),eE=a("neg_infinity"),eF=a(cb),eD=a(al),en=a("%+nd"),eo=a("% nd"),eq=a("%+ni"),er=a("% ni"),es=a("%nx"),et=a("%#nx"),eu=a("%nX"),ev=a("%#nX"),ew=a("%no"),ex=a("%#no"),em=a("%nd"),ep=a(cl),ey=a("%nu"),ea=a("%+ld"),eb=a("% ld"),ed=a("%+li"),ee=a("% li"),ef=a("%lx"),eg=a("%#lx"),eh=a("%lX"),ei=a("%#lX"),ej=a("%lo"),ek=a("%#lo"),d$=a("%ld"),ec=a(b_),el=a("%lu"),dZ=a("%+Ld"),d0=a("% Ld"),d2=a("%+Li"),d3=a("% Li"),d4=a("%Lx"),d5=a("%#Lx"),d6=a("%LX"),d7=a("%#LX"),d8=a("%Lo"),d9=a("%#Lo"),dY=a("%Ld"),d1=a(bM),d_=a("%Lu"),dM=a("%+d"),dN=a("% d"),dP=a("%+i"),dQ=a("% i"),dR=a("%x"),dS=a("%#x"),dT=a("%X"),dU=a("%#X"),dV=a("%o"),dW=a("%#o"),dL=a(bV),dO=a(bF),dX=a(ch),c5=a("@]"),c6=a("@}"),c7=a("@?"),c8=a("@\n"),c9=a("@."),c_=a("@@"),c$=a("@%"),da=a("@"),dJ=a("CamlinternalFormat.Type_mismatch"),eV=a("Js_of_ocaml__Js.Error"),eW=[0,[11,a("Hello "),[2,0,[11,a(", I'm OCaml!"),0]]],a("Hello %s, I'm OCaml!")];function
k(a){if(typeof
a==="number")return 0;else
switch(a[0]){case
0:return[0,k(a[1])];case
1:return[1,k(a[1])];case
2:return[2,k(a[1])];case
3:return[3,k(a[1])];case
4:return[4,k(a[1])];case
5:return[5,k(a[1])];case
6:return[6,k(a[1])];case
7:return[7,k(a[1])];case
8:var
c=a[1];return[8,c,k(a[2])];case
9:var
b=a[1];return[9,b,b,k(a[3])];case
10:return[10,k(a[1])];case
11:return[11,k(a[1])];case
12:return[12,k(a[1])];case
13:return[13,k(a[1])];default:return[14,k(a[1])]}}function
z(a,b){if(typeof
a==="number")return b;else
switch(a[0]){case
0:return[0,z(a[1],b)];case
1:return[1,z(a[1],b)];case
2:return[2,z(a[1],b)];case
3:return[3,z(a[1],b)];case
4:return[4,z(a[1],b)];case
5:return[5,z(a[1],b)];case
6:return[6,z(a[1],b)];case
7:return[7,z(a[1],b)];case
8:var
c=a[1];return[8,c,z(a[2],b)];case
9:var
d=a[2],e=a[1];return[9,e,d,z(a[3],b)];case
10:return[10,z(a[1],b)];case
11:return[11,z(a[1],b)];case
12:return[12,z(a[1],b)];case
13:return[13,z(a[1],b)];default:return[14,z(a[1],b)]}}function
j(a,b){if(typeof
a==="number")return b;else
switch(a[0]){case
0:return[0,j(a[1],b)];case
1:return[1,j(a[1],b)];case
2:var
c=a[1];return[2,c,j(a[2],b)];case
3:var
d=a[1];return[3,d,j(a[2],b)];case
4:var
e=a[3],f=a[2],g=a[1];return[4,g,f,e,j(a[4],b)];case
5:var
h=a[3],i=a[2],k=a[1];return[5,k,i,h,j(a[4],b)];case
6:var
l=a[3],m=a[2],n=a[1];return[6,n,m,l,j(a[4],b)];case
7:var
o=a[3],p=a[2],q=a[1];return[7,q,p,o,j(a[4],b)];case
8:var
r=a[3],s=a[2],t=a[1];return[8,t,s,r,j(a[4],b)];case
9:var
u=a[1];return[9,u,j(a[2],b)];case
10:return[10,j(a[1],b)];case
11:var
v=a[1];return[11,v,j(a[2],b)];case
12:var
w=a[1];return[12,w,j(a[2],b)];case
13:var
x=a[2],y=a[1];return[13,y,x,j(a[3],b)];case
14:var
z=a[2],A=a[1];return[14,A,z,j(a[3],b)];case
15:return[15,j(a[1],b)];case
16:return[16,j(a[1],b)];case
17:var
B=a[1];return[17,B,j(a[2],b)];case
18:var
C=a[1];return[18,C,j(a[2],b)];case
19:return[19,j(a[1],b)];case
20:var
D=a[2],E=a[1];return[20,E,D,j(a[3],b)];case
21:var
F=a[1];return[21,F,j(a[2],b)];case
22:return[22,j(a[1],b)];case
23:var
G=a[1];return[23,G,j(a[2],b)];default:var
H=a[2],I=a[1];return[24,I,H,j(a[3],b)]}}function
aH(a){throw[0,bo,a]}aB(0);function
aU(a){return 0<=a?a:-a|0}function
br(d,c){var
a=y(d),e=y(c),b=u(a+e|0);ag(d,0,b,0,a);ag(c,0,b,a,e);return F(b)}function
cP(a){return a?cQ:cR}fq(0);cG(1);cG(2);var
as=(4*fB(0)|0)-1|0;aB(0);typeof
fA(0)==="number";function
ad(a,c){var
b=u(a);e5(b,0,a,c);return b}function
bs(d,b,a){var
f=0;if(0<=b&&0<=a&&!((J(d)-a|0)<b)){var
c=u(a);af(d,b,c,0,a);var
e=c;f=1}if(!f)var
e=aH(cZ);return F(e)}function
bt(e,c,d,b,a){if(0<=a&&0<=c&&!((J(e)-a|0)<c)&&0<=b&&!((J(d)-a|0)<b))return af(e,c,d,b,a);return aH(c0)}function
R(e,c,d,b,a){if(0<=a&&0<=c&&!((y(e)-a|0)<c)&&0<=b&&!((J(d)-a|0)<b))return ag(e,c,d,b,a);return aH(c1)}aB(0);function
bu(a,c){var
d=a[2],b=[0,a[3]];for(;;){if(b[1]<(d+c|0)){b[1]=2*b[1]|0;continue}if(as<b[1]){if(!((d+c|0)<=as))throw[0,bp,c4];b[1]=as}var
e=u(b[1]);bt(a[1],0,e,0,a[2]);a[1]=e;a[3]=b[1];if((a[2]+c|0)<=a[3]){if((d+c|0)<=a[3])return 0;throw[0,l,c2]}throw[0,l,c3]}}function
at(a,c){var
b=y(c),d=a[2]+b|0;if(a[3]<d)bu(a,b);ag(c,0,a[1],a[2],b);a[2]=d;return 0}function
aV(a){return 5===a[2]?12:-6}function
bv(a){return[0,0,u(a)]}function
bw(a,h){var
b=J(a[2]),c=a[1]+h|0,d=b<c?1:0;if(d){var
e=b*2|0,i=e7(e,c)?e:c,f=u(i);bt(a[2],0,f,0,b);a[2]=f;var
g=0}else
var
g=d;return g}function
ai(a,b){bw(a,1);ah(a[2],a[1],b);a[1]=a[1]+1|0;return 0}function
w(a,c){var
b=y(c);bw(a,b);R(c,0,a[2],a[1],b);a[1]=a[1]+b|0;return 0}function
bx(a){return bs(a[2],0,a[1])}function
aW(b,c){var
a=c;for(;;)if(typeof
a==="number")return 0;else
switch(a[0]){case
0:var
d=a[1];w(b,db);var
a=d;continue;case
1:var
e=a[1];w(b,dc);var
a=e;continue;case
2:var
f=a[1];w(b,dd);var
a=f;continue;case
3:var
g=a[1];w(b,de);var
a=g;continue;case
4:var
h=a[1];w(b,df);var
a=h;continue;case
5:var
i=a[1];w(b,dg);var
a=i;continue;case
6:var
j=a[1];w(b,dh);var
a=j;continue;case
7:var
k=a[1];w(b,di);var
a=k;continue;case
8:var
l=a[2],m=a[1];w(b,dj);aW(b,m);w(b,dk);var
a=l;continue;case
9:var
n=a[3],o=a[1];w(b,dl);aW(b,o);w(b,dm);var
a=n;continue;case
10:var
p=a[1];w(b,dn);var
a=p;continue;case
11:var
q=a[1];w(b,dp);var
a=q;continue;case
12:var
r=a[1];w(b,dq);var
a=r;continue;case
13:var
s=a[1];w(b,dr);var
a=s;continue;default:var
t=a[1];w(b,ds);var
a=t;continue}}function
o(a){if(typeof
a==="number")return 0;else
switch(a[0]){case
0:return[0,o(a[1])];case
1:return[1,o(a[1])];case
2:return[2,o(a[1])];case
3:return[3,o(a[1])];case
4:return[4,o(a[1])];case
5:return[5,o(a[1])];case
6:return[6,o(a[1])];case
7:return[7,o(a[1])];case
8:var
b=a[1];return[8,b,o(a[2])];case
9:var
c=a[2],d=a[1];return[9,c,d,o(a[3])];case
10:return[10,o(a[1])];case
11:return[11,o(a[1])];case
12:return[12,o(a[1])];case
13:return[13,o(a[1])];default:return[14,o(a[1])]}}function
x(a){if(typeof
a==="number"){var
u=function(a){return 0},v=function(a){return 0},w=function(a){return 0};return[0,function(a){return 0},w,v,u]}else
switch(a[0]){case
0:var
b=x(a[1]),y=b[4],z=b[3],A=b[2],B=b[1],C=function(a){d(A,0);return 0};return[0,function(a){d(B,0);return 0},C,z,y];case
1:var
c=x(a[1]),D=c[4],E=c[3],F=c[2],G=c[1],H=function(a){d(F,0);return 0};return[0,function(a){d(G,0);return 0},H,E,D];case
2:var
e=x(a[1]),I=e[4],J=e[3],K=e[2],L=e[1],M=function(a){d(K,0);return 0};return[0,function(a){d(L,0);return 0},M,J,I];case
3:var
f=x(a[1]),N=f[4],O=f[3],P=f[2],Q=f[1],R=function(a){d(P,0);return 0};return[0,function(a){d(Q,0);return 0},R,O,N];case
4:var
g=x(a[1]),S=g[4],T=g[3],U=g[2],V=g[1],W=function(a){d(U,0);return 0};return[0,function(a){d(V,0);return 0},W,T,S];case
5:var
h=x(a[1]),X=h[4],Y=h[3],Z=h[2],_=h[1],$=function(a){d(Z,0);return 0};return[0,function(a){d(_,0);return 0},$,Y,X];case
6:var
i=x(a[1]),aa=i[4],ab=i[3],ac=i[2],ad=i[1],ae=function(a){d(ac,0);return 0};return[0,function(a){d(ad,0);return 0},ae,ab,aa];case
7:var
j=x(a[1]),af=j[4],ag=j[3],ah=j[2],ai=j[1],aj=function(a){d(ah,0);return 0};return[0,function(a){d(ai,0);return 0},aj,ag,af];case
8:var
k=x(a[2]),ak=k[4],al=k[3],am=k[2],an=k[1],ao=function(a){d(am,0);return 0};return[0,function(a){d(an,0);return 0},ao,al,ak];case
9:var
ap=a[2],aq=a[1],l=x(a[3]),ar=l[4],as=l[3],at=l[2],au=l[1],m=x(p(o(aq),ap)),av=m[4],aw=m[3],ax=m[2],ay=m[1],az=function(a){d(av,0);d(ar,0);return 0},aA=function(a){d(as,0);d(aw,0);return 0},aB=function(a){d(ax,0);d(at,0);return 0};return[0,function(a){d(au,0);d(ay,0);return 0},aB,aA,az];case
10:var
n=x(a[1]),aC=n[4],aD=n[3],aE=n[2],aF=n[1],aG=function(a){d(aE,0);return 0};return[0,function(a){d(aF,0);return 0},aG,aD,aC];case
11:var
q=x(a[1]),aH=q[4],aI=q[3],aJ=q[2],aK=q[1],aL=function(a){d(aJ,0);return 0};return[0,function(a){d(aK,0);return 0},aL,aI,aH];case
12:var
r=x(a[1]),aM=r[4],aN=r[3],aO=r[2],aP=r[1],aQ=function(a){d(aO,0);return 0};return[0,function(a){d(aP,0);return 0},aQ,aN,aM];case
13:var
s=x(a[1]),aR=s[4],aS=s[3],aT=s[2],aU=s[1],aV=function(a){d(aR,0);return 0},aW=function(a){d(aS,0);return 0},aX=function(a){d(aT,0);return 0};return[0,function(a){d(aU,0);return 0},aX,aW,aV];default:var
t=x(a[1]),aY=t[4],aZ=t[3],a0=t[2],a1=t[1],a2=function(a){d(aY,0);return 0},a3=function(a){d(aZ,0);return 0},a4=function(a){d(a0,0);return 0};return[0,function(a){d(a1,0);return 0},a4,a3,a2]}}function
p(c,b){var
a=0;if(typeof
c==="number")if(typeof
b==="number")return 0;else
switch(b[0]){case
10:break;case
11:a=1;break;case
12:a=2;break;case
13:a=3;break;case
14:a=4;break;case
8:a=5;break;case
9:a=6;break;default:throw[0,l,dt]}else
switch(c[0]){case
0:var
e=0,w=c[1];if(typeof
b!=="number")switch(b[0]){case
0:return[0,p(w,b[1])];case
8:a=5;e=1;break;case
9:a=6;e=1;break;case
10:e=1;break;case
11:a=1;e=1;break;case
12:a=2;e=1;break;case
13:a=3;e=1;break;case
14:a=4;e=1;break}if(!e)a=7;break;case
1:var
f=0,y=c[1];if(typeof
b!=="number")switch(b[0]){case
1:return[1,p(y,b[1])];case
8:a=5;f=1;break;case
9:a=6;f=1;break;case
10:f=1;break;case
11:a=1;f=1;break;case
12:a=2;f=1;break;case
13:a=3;f=1;break;case
14:a=4;f=1;break}if(!f)a=7;break;case
2:var
g=0,z=c[1];if(typeof
b==="number")g=1;else
switch(b[0]){case
2:return[2,p(z,b[1])];case
8:a=5;break;case
9:a=6;break;case
10:break;case
11:a=1;break;case
12:a=2;break;case
13:a=3;break;case
14:a=4;break;default:g=1}if(g)a=7;break;case
3:var
h=0,A=c[1];if(typeof
b==="number")h=1;else
switch(b[0]){case
3:return[3,p(A,b[1])];case
8:a=5;break;case
9:a=6;break;case
10:break;case
11:a=1;break;case
12:a=2;break;case
13:a=3;break;case
14:a=4;break;default:h=1}if(h)a=7;break;case
4:var
i=0,B=c[1];if(typeof
b==="number")i=1;else
switch(b[0]){case
4:return[4,p(B,b[1])];case
8:a=5;break;case
9:a=6;break;case
10:break;case
11:a=1;break;case
12:a=2;break;case
13:a=3;break;case
14:a=4;break;default:i=1}if(i)a=7;break;case
5:var
j=0,C=c[1];if(typeof
b==="number")j=1;else
switch(b[0]){case
5:return[5,p(C,b[1])];case
8:a=5;break;case
9:a=6;break;case
10:break;case
11:a=1;break;case
12:a=2;break;case
13:a=3;break;case
14:a=4;break;default:j=1}if(j)a=7;break;case
6:var
k=0,D=c[1];if(typeof
b==="number")k=1;else
switch(b[0]){case
6:return[6,p(D,b[1])];case
8:a=5;break;case
9:a=6;break;case
10:break;case
11:a=1;break;case
12:a=2;break;case
13:a=3;break;case
14:a=4;break;default:k=1}if(k)a=7;break;case
7:var
m=0,E=c[1];if(typeof
b==="number")m=1;else
switch(b[0]){case
7:return[7,p(E,b[1])];case
8:a=5;break;case
9:a=6;break;case
10:break;case
11:a=1;break;case
12:a=2;break;case
13:a=3;break;case
14:a=4;break;default:m=1}if(m)a=7;break;case
8:var
n=0,F=c[2],G=c[1];if(typeof
b==="number")n=1;else
switch(b[0]){case
8:var
H=b[1],I=p(F,b[2]);return[8,p(G,H),I];case
10:break;case
11:a=1;break;case
12:a=2;break;case
13:a=3;break;case
14:a=4;break;default:n=1}if(n)throw[0,l,dC];break;case
9:var
q=0,J=c[3],K=c[2],L=c[1];if(typeof
b==="number")q=1;else
switch(b[0]){case
8:a=5;break;case
9:var
M=b[3],N=b[2],O=b[1],v=x(p(o(K),O)),P=v[4];d(v[2],0);d(P,0);return[9,L,N,p(J,M)];case
10:break;case
11:a=1;break;case
12:a=2;break;case
13:a=3;break;case
14:a=4;break;default:q=1}if(q)throw[0,l,dD];break;case
10:var
Q=c[1];if(typeof
b!=="number"&&10===b[0])return[10,p(Q,b[1])];throw[0,l,dE];case
11:var
r=0,R=c[1];if(typeof
b==="number")r=1;else
switch(b[0]){case
10:break;case
11:return[11,p(R,b[1])];default:r=1}if(r)throw[0,l,dF];break;case
12:var
s=0,S=c[1];if(typeof
b==="number")s=1;else
switch(b[0]){case
10:break;case
11:a=1;break;case
12:return[12,p(S,b[1])];default:s=1}if(s)throw[0,l,dG];break;case
13:var
t=0,T=c[1];if(typeof
b==="number")t=1;else
switch(b[0]){case
10:break;case
11:a=1;break;case
12:a=2;break;case
13:return[13,p(T,b[1])];default:t=1}if(t)throw[0,l,dH];break;default:var
u=0,U=c[1];if(typeof
b==="number")u=1;else
switch(b[0]){case
10:break;case
11:a=1;break;case
12:a=2;break;case
13:a=3;break;case
14:return[14,p(U,b[1])];default:u=1}if(u)throw[0,l,dI]}switch(a){case
0:throw[0,l,dw];case
1:throw[0,l,dx];case
2:throw[0,l,dy];case
3:throw[0,l,dz];case
4:throw[0,l,dA];case
5:throw[0,l,du];case
6:throw[0,l,dv];default:throw[0,l,dB]}}var
s=[B,dJ,aB(0)];function
aI(b,a){if(typeof
b==="number")return[0,0,a];else{if(0===b[0])return[0,[0,b[1],b[2]],a];if(typeof
a!=="number"&&2===a[0])return[0,[1,b[1]],a[1]];throw s}}function
au(e,b,d){var
a=aI(e,d);if(typeof
b==="number"){if(b){var
c=a[2];if(typeof
c!=="number"&&2===c[0])return[0,a[1],1,c[1]];throw s}return[0,a[1],0,a[2]]}return[0,a[1],[0,b[1]],a[2]]}function
A(b,c,a){if(typeof
b==="number")return[0,0,i(c,a)];else
switch(b[0]){case
0:if(typeof
a!=="number"&&0===a[0]){var
g=A(b[1],c,a[1]);return[0,[0,g[1]],g[2]]}break;case
1:if(typeof
a!=="number"&&1===a[0]){var
h=A(b[1],c,a[1]);return[0,[1,h[1]],h[2]]}break;case
2:if(typeof
a!=="number"&&2===a[0]){var
j=A(b[1],c,a[1]);return[0,[2,j[1]],j[2]]}break;case
3:if(typeof
a!=="number"&&3===a[0]){var
l=A(b[1],c,a[1]);return[0,[3,l[1]],l[2]]}break;case
4:if(typeof
a!=="number"&&4===a[0]){var
m=A(b[1],c,a[1]);return[0,[4,m[1]],m[2]]}break;case
5:if(typeof
a!=="number"&&5===a[0]){var
n=A(b[1],c,a[1]);return[0,[5,n[1]],n[2]]}break;case
6:if(typeof
a!=="number"&&6===a[0]){var
q=A(b[1],c,a[1]);return[0,[6,q[1]],q[2]]}break;case
7:if(typeof
a!=="number"&&7===a[0]){var
r=A(b[1],c,a[1]);return[0,[7,r[1]],r[2]]}break;case
8:if(typeof
a!=="number"&&8===a[0]){var
t=a[1],D=a[2],E=b[2];if(aE([0,b[1]],[0,t]))throw s;var
u=A(E,c,D);return[0,[8,t,u[1]],u[2]]}break;case
9:if(typeof
a!=="number"&&9===a[0]){var
e=a[2],f=a[1],F=a[3],G=b[3],H=b[2],I=b[1],J=[0,k(f)];if(aE([0,k(I)],J))throw s;var
K=[0,k(e)];if(aE([0,k(H)],K))throw s;var
v=x(p(o(f),e)),L=v[4];d(v[2],0);d(L,0);var
w=A(k(G),c,F),M=w[2];return[0,[9,f,e,o(w[1])],M]}break;case
10:if(typeof
a!=="number"&&10===a[0]){var
y=A(b[1],c,a[1]);return[0,[10,y[1]],y[2]]}break;case
11:if(typeof
a!=="number"&&11===a[0]){var
z=A(b[1],c,a[1]);return[0,[11,z[1]],z[2]]}break;case
13:if(typeof
a!=="number"&&13===a[0]){var
B=A(b[1],c,a[1]);return[0,[13,B[1]],B[2]]}break;case
14:if(typeof
a!=="number"&&14===a[0]){var
C=A(b[1],c,a[1]);return[0,[14,C[1]],C[2]]}break}throw s}function
i(b,a){if(typeof
b==="number")return[0,0,a];else
switch(b[0]){case
0:if(typeof
a!=="number"&&0===a[0]){var
v=i(b[1],a[1]);return[0,[0,v[1]],v[2]]}break;case
1:if(typeof
a!=="number"&&0===a[0]){var
w=i(b[1],a[1]);return[0,[1,w[1]],w[2]]}break;case
2:var
af=b[2],x=aI(b[1],a),e=x[2],ag=x[1];if(typeof
e!=="number"&&1===e[0]){var
y=i(af,e[1]);return[0,[2,ag,y[1]],y[2]]}throw s;case
3:var
ah=b[2],z=aI(b[1],a),f=z[2],ai=z[1];if(typeof
f!=="number"&&1===f[0]){var
B=i(ah,f[1]);return[0,[3,ai,B[1]],B[2]]}throw s;case
4:var
aj=b[4],ak=b[1],g=au(b[2],b[3],a),h=g[3],al=g[1];if(typeof
h!=="number"&&2===h[0]){var
am=g[2],D=i(aj,h[1]);return[0,[4,ak,al,am,D[1]],D[2]]}throw s;case
5:var
an=b[4],ao=b[1],j=au(b[2],b[3],a),l=j[3],ap=j[1];if(typeof
l!=="number"&&3===l[0]){var
aq=j[2],E=i(an,l[1]);return[0,[5,ao,ap,aq,E[1]],E[2]]}throw s;case
6:var
ar=b[4],as=b[1],m=au(b[2],b[3],a),n=m[3],at=m[1];if(typeof
n!=="number"&&4===n[0]){var
av=m[2],F=i(ar,n[1]);return[0,[6,as,at,av,F[1]],F[2]]}throw s;case
7:var
aw=b[4],ax=b[1],o=au(b[2],b[3],a),p=o[3],ay=o[1];if(typeof
p!=="number"&&5===p[0]){var
az=o[2],G=i(aw,p[1]);return[0,[7,ax,ay,az,G[1]],G[2]]}throw s;case
8:var
aA=b[4],aB=b[1],q=au(b[2],b[3],a),r=q[3],aC=q[1];if(typeof
r!=="number"&&6===r[0]){var
aD=q[2],H=i(aA,r[1]);return[0,[8,aB,aC,aD,H[1]],H[2]]}throw s;case
9:var
aF=b[2],I=aI(b[1],a),t=I[2],aG=I[1];if(typeof
t!=="number"&&7===t[0]){var
J=i(aF,t[1]);return[0,[9,aG,J[1]],J[2]]}throw s;case
10:var
K=i(b[1],a);return[0,[10,K[1]],K[2]];case
11:var
aH=b[1],L=i(b[2],a);return[0,[11,aH,L[1]],L[2]];case
12:var
aJ=b[1],M=i(b[2],a);return[0,[12,aJ,M[1]],M[2]];case
13:if(typeof
a!=="number"&&8===a[0]){var
N=a[1],aK=a[2],aL=b[3],aM=b[1];if(aE([0,b[2]],[0,N]))throw s;var
O=i(aL,aK);return[0,[13,aM,N,O[1]],O[2]]}break;case
14:if(typeof
a!=="number"&&9===a[0]){var
P=a[1],aN=a[3],aO=b[3],aP=b[2],aQ=b[1],aR=[0,k(P)];if(aE([0,k(aP)],aR))throw s;var
Q=i(aO,k(aN));return[0,[14,aQ,P,Q[1]],Q[2]]}break;case
15:if(typeof
a!=="number"&&10===a[0]){var
R=i(b[1],a[1]);return[0,[15,R[1]],R[2]]}break;case
16:if(typeof
a!=="number"&&11===a[0]){var
S=i(b[1],a[1]);return[0,[16,S[1]],S[2]]}break;case
17:var
aS=b[1],T=i(b[2],a);return[0,[17,aS,T[1]],T[2]];case
18:var
U=b[2],u=b[1];if(0===u[0]){var
Y=u[1],aW=Y[2],Z=i(Y[1],a),aX=Z[1],_=i(U,Z[2]);return[0,[18,[0,[0,aX,aW]],_[1]],_[2]]}var
$=u[1],aY=$[2],aa=i($[1],a),aZ=aa[1],ab=i(U,aa[2]);return[0,[18,[1,[0,aZ,aY]],ab[1]],ab[2]];case
19:if(typeof
a!=="number"&&13===a[0]){var
V=i(b[1],a[1]);return[0,[19,V[1]],V[2]]}break;case
20:if(typeof
a!=="number"&&1===a[0]){var
aT=b[2],aU=b[1],W=i(b[3],a[1]);return[0,[20,aU,aT,W[1]],W[2]]}break;case
21:if(typeof
a!=="number"&&2===a[0]){var
aV=b[1],X=i(b[2],a[1]);return[0,[21,aV,X[1]],X[2]]}break;case
23:var
d=b[2],c=b[1];if(typeof
c==="number")switch(c){case
0:return C(c,d,a);case
1:return C(c,d,a);case
2:if(typeof
a!=="number"&&14===a[0]){var
ac=i(d,a[1]);return[0,[23,2,ac[1]],ac[2]]}throw s;default:return C(c,d,a)}else
switch(c[0]){case
0:return C(c,d,a);case
1:return C(c,d,a);case
2:return C(c,d,a);case
3:return C(c,d,a);case
4:return C(c,d,a);case
5:return C(c,d,a);case
6:return C(c,d,a);case
7:return C(c,d,a);case
8:return C([8,c[1],c[2]],d,a);case
9:var
a0=c[1],ad=A(c[2],d,a),ae=ad[2];return[0,[23,[9,a0,ad[1]],ae[1]],ae[2]];case
10:return C(c,d,a);default:return C(c,d,a)}}throw s}function
C(d,c,b){var
a=i(c,b);return[0,[23,d,a[1]],a[2]]}function
D(k,g,a){var
b=y(a),h=0<=g?k:0,d=aU(g);if(d<=b)return a;var
l=2===h?48:32,c=ad(d,l);switch(h){case
0:R(a,0,c,0,b);break;case
1:R(a,0,c,d-b|0,b);break;default:var
e=0;if(0<b){var
i=0;if(43!==H(a,0)&&45!==H(a,0)&&32!==H(a,0)){e=1;i=1}if(!i){ah(c,0,H(a,0));R(a,1,c,(d-b|0)+1|0,b-1|0)}}else
e=1;if(e){var
f=0;if(1<b&&48===H(a,0)){var
j=0;if(bS!==H(a,1)&&88!==H(a,1)){f=1;j=1}if(!j){ah(c,1,H(a,1));R(a,2,c,(d-b|0)+2|0,b-2|0)}}else
f=1;if(f)R(a,0,c,d-b|0,b)}}return F(c)}function
aj(k,b){var
c=aU(k),a=y(b),d=H(b,0),e=0;if(58<=d){if(71<=d){if(!(5<(d+bK|0)>>>0))e=1}else
if(65<=d)e=1}else{var
f=0;if(32!==d)if(43<=d)switch(d-43|0){case
5:if(a<(c+2|0)&&1<a){var
j=0;if(bS===H(b,1)||88===H(b,1))j=1;if(j){var
h=ad(c+2|0,48);ah(h,1,H(b,1));R(b,2,h,(c-a|0)+4|0,a-2|0);return F(h)}}e=1;f=1;break;case
0:case
2:break;case
1:case
3:case
4:f=1;break;default:e=1;f=1}else
f=1;if(!f&&a<(c+1|0)){var
g=ad(c+1|0,48);ah(g,0,d);R(b,1,g,(c-a|0)+2|0,a-1|0);return F(g)}}if(e&&a<c){var
i=ad(c,48);R(b,0,i,c-a|0,a);return F(i)}return b}function
dK(k){var
j=0,G=y(k);for(;;){if(G<=j)var
p=k;else{var
o=aF(k,j)+b9|0,q=0;if(59<o>>>0){if(33<(o-61|0)>>>0)q=1}else
if(2===o)q=1;if(!q){var
j=j+1|0;continue}var
e=ao(k),a=[0,0],v=J(e)-1|0,B=0;if(!(v<0)){var
i=B;for(;;){var
f=az(e,i),g=0;if(32<=f){var
l=f-34|0,r=0;if(58<l>>>0){if(93<=l)r=1}else
if(56<(l-1|0)>>>0){g=1;r=1}if(!r){var
n=1;g=2}}else
if(11<=f){if(13===f)g=1}else
if(8<=f)g=1;switch(g){case
0:var
n=4;break;case
1:var
n=2;break}a[1]=a[1]+n|0;var
E=i+1|0;if(v!==i){var
i=E;continue}break}}if(a[1]===J(e)){var
s=J(e),t=u(s);af(e,0,t,0,s);var
x=t}else{var
b=u(a[1]);a[1]=0;var
w=J(e)-1|0,C=0;if(!(w<0)){var
h=C;for(;;){var
c=az(e,h),d=0;if(35<=c)if(92===c)d=2;else
if(a_<=c)d=1;else
d=3;else
if(32<=c)if(34<=c)d=2;else
d=3;else
if(14<=c)d=1;else
switch(c){case
8:m(b,a[1],92);a[1]++;m(b,a[1],98);break;case
9:m(b,a[1],92);a[1]++;m(b,a[1],116);break;case
10:m(b,a[1],92);a[1]++;m(b,a[1],110);break;case
13:m(b,a[1],92);a[1]++;m(b,a[1],114);break;default:d=1}switch(d){case
1:m(b,a[1],92);a[1]++;m(b,a[1],48+(c/bO|0)|0);a[1]++;m(b,a[1],48+((c/10|0)%10|0)|0);a[1]++;m(b,a[1],48+(c%10|0)|0);break;case
2:m(b,a[1],92);a[1]++;m(b,a[1],c);break;case
3:m(b,a[1],c);break}a[1]++;var
D=h+1|0;if(w!==h){var
h=D;continue}break}}var
x=b}var
p=F(x)}var
z=y(p),A=ad(z+2|0,34);ag(p,0,A,1,z);return F(A)}}function
by(d,g){var
h=aU(g),e=bz?bz[1]:70;switch(d[2]){case
0:var
b=102;break;case
1:var
b=101;break;case
2:var
b=69;break;case
3:var
b=bT;break;case
4:var
b=71;break;case
5:var
b=e;break;case
6:var
b=104;break;case
7:var
b=72;break;default:var
b=70}var
c=bv(16);ai(c,37);switch(d[1]){case
0:break;case
1:ai(c,43);break;default:ai(c,32)}if(8<=d[2])ai(c,35);ai(c,46);w(c,a(f+h));ai(c,b);return bx(c)}function
aJ(m,a){if(13<=m){var
g=[0,0],h=y(a)-1|0,n=0;if(!(h<0)){var
c=n;for(;;){if(!(9<(aF(a,c)+bY|0)>>>0))g[1]++;var
q=c+1|0;if(h!==c){var
c=q;continue}break}}var
i=g[1],j=u(y(a)+((i-1|0)/3|0)|0),k=[0,0],d=function(a){ah(j,k[1],a);k[1]++;return 0},e=[0,((i-1|0)%3|0)+1|0],l=y(a)-1|0,o=0;if(!(l<0)){var
b=o;for(;;){var
f=aF(a,b);if(9<(f+bY|0)>>>0)d(f);else{if(0===e[1]){d(95);e[1]=3}e[1]+=-1;d(f)}var
p=b+1|0;if(l!==b){var
b=p;continue}break}}return F(j)}return a}function
ez(b,c){switch(b){case
1:var
a=dM;break;case
2:var
a=dN;break;case
4:var
a=dP;break;case
5:var
a=dQ;break;case
6:var
a=dR;break;case
7:var
a=dS;break;case
8:var
a=dT;break;case
9:var
a=dU;break;case
10:var
a=dV;break;case
11:var
a=dW;break;case
0:case
13:var
a=dL;break;case
3:case
14:var
a=dO;break;default:var
a=dX}return aJ(b,aP(a,c))}function
eA(b,c){switch(b){case
1:var
a=ea;break;case
2:var
a=eb;break;case
4:var
a=ed;break;case
5:var
a=ee;break;case
6:var
a=ef;break;case
7:var
a=eg;break;case
8:var
a=eh;break;case
9:var
a=ei;break;case
10:var
a=ej;break;case
11:var
a=ek;break;case
0:case
13:var
a=d$;break;case
3:case
14:var
a=ec;break;default:var
a=el}return aJ(b,aP(a,c))}function
eB(b,c){switch(b){case
1:var
a=en;break;case
2:var
a=eo;break;case
4:var
a=eq;break;case
5:var
a=er;break;case
6:var
a=es;break;case
7:var
a=et;break;case
8:var
a=eu;break;case
9:var
a=ev;break;case
10:var
a=ew;break;case
11:var
a=ex;break;case
0:case
13:var
a=em;break;case
3:case
14:var
a=ep;break;default:var
a=ey}return aJ(b,aP(a,c))}function
eC(b,c){switch(b){case
1:var
a=dZ;break;case
2:var
a=d0;break;case
4:var
a=d2;break;case
5:var
a=d3;break;case
6:var
a=d4;break;case
7:var
a=d5;break;case
8:var
a=d6;break;case
9:var
a=d7;break;case
10:var
a=d8;break;case
11:var
a=d9;break;case
0:case
13:var
a=dY;break;case
3:case
14:var
a=d1;break;default:var
a=d_}return aJ(b,fb(a,c))}function
S(c,i,b){function
j(d){switch(c[1]){case
0:var
a=45;break;case
1:var
a=43;break;default:var
a=32}return e9(b,i,a)}function
r(c){var
a=e4(b);return 3===a?b<0.?eE:eF:4<=a?eG:c}switch(c[2]){case
5:var
e=cC(by(c,i),b),d=0,w=y(e);for(;;){if(d===w)var
q=0;else{var
k=H(e,d)-46|0,l=0;if(23<k>>>0){if(55===k)l=1}else
if(21<(k-1|0)>>>0)l=1;if(!l){var
d=d+1|0;continue}var
q=1}var
x=q?e:br(e,eD);return r(x)}case
6:return j(0);case
7:var
h=ao(j(0)),f=J(h);if(0===f)var
p=h;else{var
n=u(f),o=f-1|0,s=0;if(!(o<0)){var
a=s;for(;;){var
g=az(h,a),t=25<(g+bK|0)>>>0?g:g+b9|0;m(n,a,t);var
v=a+1|0;if(o!==a){var
a=v;continue}break}}var
p=n}return F(p);case
8:return r(j(0));default:return cC(by(c,i),b)}}function
av(f,L,K,J){var
b=L,a=K,c=J;for(;;)if(typeof
c==="number")return d(b,a);else
switch(c[0]){case
0:var
N=c[1];return function(c){return e(b,[5,a,c],N)};case
1:var
O=c[1];return function(c){var
f=0;if(40<=c)if(92===c)var
d=cT;else
if(a_<=c)f=1;else
f=2;else
if(32<=c)if(39<=c)var
d=cU;else
f=2;else
if(14<=c)f=1;else
switch(c){case
8:var
d=cV;break;case
9:var
d=cW;break;case
10:var
d=cX;break;case
13:var
d=cY;break;default:f=1}switch(f){case
1:var
g=u(4);m(g,0,92);m(g,1,48+(c/bO|0)|0);m(g,2,48+((c/10|0)%10|0)|0);m(g,3,48+(c%10|0)|0);var
d=F(g);break;case
2:var
h=u(1);m(h,0,c);var
d=F(h);break}var
i=y(d),j=ad(i+2|0,39);ag(d,0,j,1,i);return e(b,[4,a,F(j)],O)};case
2:var
P=c[2],Q=c[1];return aX(b,a,P,Q,function(a){return a});case
3:return aX(b,a,c[2],c[1],dK);case
4:return aK(b,a,c[4],c[2],c[3],ez,c[1]);case
5:return aK(b,a,c[4],c[2],c[3],eA,c[1]);case
6:return aK(b,a,c[4],c[2],c[3],eB,c[1]);case
7:return aK(b,a,c[4],c[2],c[3],eC,c[1]);case
8:var
p=c[4],q=c[3],r=c[2],n=c[1];if(typeof
r==="number"){if(typeof
q==="number")return q?function(d,c){return e(b,[4,a,S(n,d,c)],p)}:function(c){return e(b,[4,a,S(n,aV(n),c)],p)};var
ai=q[1];return function(c){return e(b,[4,a,S(n,ai,c)],p)}}else{if(0===r[0]){var
x=r[2],z=r[1];if(typeof
q==="number")return q?function(d,c){return e(b,[4,a,D(z,x,S(n,d,c))],p)}:function(c){return e(b,[4,a,D(z,x,S(n,aV(n),c))],p)};var
aj=q[1];return function(c){return e(b,[4,a,D(z,x,S(n,aj,c))],p)}}var
A=r[1];if(typeof
q==="number")return q?function(f,d,c){return e(b,[4,a,D(A,f,S(n,d,c))],p)}:function(d,c){return e(b,[4,a,D(A,d,S(n,aV(n),c))],p)};var
ak=q[1];return function(d,c){return e(b,[4,a,D(A,d,S(n,ak,c))],p)}}case
9:return aX(b,a,c[2],c[1],cP);case
10:var
a=[7,a],c=c[1];continue;case
11:var
a=[2,a,c[1]],c=c[2];continue;case
12:var
a=[3,a,c[1]],c=c[2];continue;case
13:var
R=c[3],T=c[2],B=bv(16);aW(B,T);var
I=bx(B);return function(c){return e(b,[4,a,I],R)};case
14:var
U=c[3],V=c[2];return function(d){var
f=d[1],c=i(f,k(o(V)));if(typeof
c[2]==="number")return e(b,a,j(c[1],U));throw s};case
15:var
W=c[1];return function(d,c){return e(b,[6,a,function(a){return M(d,a,c)}],W)};case
16:var
X=c[1];return function(c){return e(b,[6,a,c],X)};case
17:var
a=[0,a,c[1]],c=c[2];continue;case
18:var
w=c[1];if(0===w[0]){var
Y=c[2],Z=w[1][1],_=0,b=function(b,c,d){return function(a){return e(c,[1,b,[0,a]],d)}}(a,b,Y),a=_,c=Z;continue}var
$=c[2],aa=w[1][1],ab=0,b=function(b,c,d){return function(a){return e(c,[1,b,[1,a]],d)}}(a,b,$),a=ab,c=aa;continue;case
19:throw[0,l,eI];case
20:var
ac=c[3],ae=[8,a,eJ];return function(a){return e(b,ae,ac)};case
21:var
af=c[2];return function(c){return e(b,[4,a,aP(eK,c)],af)};case
22:var
ah=c[1];return function(c){return e(b,[5,a,c],ah)};case
23:var
g=c[2],t=c[1];if(typeof
t==="number")switch(t){case
0:return f<50?h(f+1|0,b,a,g):v(h,[0,b,a,g]);case
1:return f<50?h(f+1|0,b,a,g):v(h,[0,b,a,g]);case
2:throw[0,l,eL];default:return f<50?h(f+1|0,b,a,g):v(h,[0,b,a,g])}else
switch(t[0]){case
0:return f<50?h(f+1|0,b,a,g):v(h,[0,b,a,g]);case
1:return f<50?h(f+1|0,b,a,g):v(h,[0,b,a,g]);case
2:return f<50?h(f+1|0,b,a,g):v(h,[0,b,a,g]);case
3:return f<50?h(f+1|0,b,a,g):v(h,[0,b,a,g]);case
4:return f<50?h(f+1|0,b,a,g):v(h,[0,b,a,g]);case
5:return f<50?h(f+1|0,b,a,g):v(h,[0,b,a,g]);case
6:return f<50?h(f+1|0,b,a,g):v(h,[0,b,a,g]);case
7:return f<50?h(f+1|0,b,a,g):v(h,[0,b,a,g]);case
8:return f<50?h(f+1|0,b,a,g):v(h,[0,b,a,g]);case
9:var
H=t[2];return f<50?a0(f+1|0,b,a,H,g):v(a0,[0,b,a,H,g]);case
10:return f<50?h(f+1|0,b,a,g):v(h,[0,b,a,g]);default:return f<50?h(f+1|0,b,a,g):v(h,[0,b,a,g])}default:var
C=c[3],E=c[1],G=d(c[2],0);return f<50?aZ(f+1|0,b,a,C,E,G):v(aZ,[0,b,a,C,E,G])}}function
a0(e,d,c,a,b){if(typeof
a==="number")return e<50?h(e+1|0,d,c,b):v(h,[0,d,c,b]);else
switch(a[0]){case
0:var
f=a[1];return function(a){return G(d,c,f,b)};case
1:var
g=a[1];return function(a){return G(d,c,g,b)};case
2:var
i=a[1];return function(a){return G(d,c,i,b)};case
3:var
j=a[1];return function(a){return G(d,c,j,b)};case
4:var
k=a[1];return function(a){return G(d,c,k,b)};case
5:var
m=a[1];return function(a){return G(d,c,m,b)};case
6:var
n=a[1];return function(a){return G(d,c,n,b)};case
7:var
q=a[1];return function(a){return G(d,c,q,b)};case
8:var
r=a[2];return function(a){return G(d,c,r,b)};case
9:var
s=a[3],t=a[2],u=p(o(a[1]),t);return function(a){return G(d,c,z(u,s),b)};case
10:var
w=a[1];return function(e,a){return G(d,c,w,b)};case
11:var
x=a[1];return function(a){return G(d,c,x,b)};case
12:var
y=a[1];return function(a){return G(d,c,y,b)};case
13:throw[0,l,eM];default:throw[0,l,eN]}}function
h(d,b,e,a){var
c=[8,e,eO];return d<50?av(d+1|0,b,c,a):v(av,[0,b,c,a])}function
aZ(h,b,f,a,e,c){if(e){var
i=e[1];return function(e){return eH(b,f,a,i,d(c,e))}}var
g=[4,f,c];return h<50?av(h+1|0,b,g,a):v(av,[0,b,g,a])}function
e(a,b,c){return bm(av(0,a,b,c))}function
G(a,b,c,d){return bm(a0(0,a,b,c,d))}function
eH(a,b,c,d,e){return bm(aZ(0,a,b,c,d,e))}function
aX(g,f,c,a,b){if(typeof
a==="number")return function(a){return e(g,[4,f,d(b,a)],c)};else{if(0===a[0]){var
h=a[2],i=a[1];return function(a){return e(g,[4,f,D(i,h,d(b,a))],c)}}var
j=a[1];return function(h,a){return e(g,[4,f,D(j,h,d(b,a))],c)}}}function
aK(g,f,d,h,c,b,a){if(typeof
h==="number"){if(typeof
c==="number")return c?function(h,c){return e(g,[4,f,aj(h,M(b,a,c))],d)}:function(c){return e(g,[4,f,M(b,a,c)],d)};var
l=c[1];return function(c){return e(g,[4,f,aj(l,M(b,a,c))],d)}}else{if(0===h[0]){var
i=h[2],j=h[1];if(typeof
c==="number")return c?function(h,c){return e(g,[4,f,D(j,i,aj(h,M(b,a,c)))],d)}:function(c){return e(g,[4,f,D(j,i,M(b,a,c))],d)};var
m=c[1];return function(c){return e(g,[4,f,D(j,i,aj(m,M(b,a,c)))],d)}}var
k=h[1];if(typeof
c==="number")return c?function(i,h,c){return e(g,[4,f,D(k,i,aj(h,M(b,a,c)))],d)}:function(h,c){return e(g,[4,f,D(k,h,M(b,a,c))],d)};var
n=c[1];return function(h,c){return e(g,[4,f,D(k,h,aj(n,M(b,a,c)))],d)}}}function
_(b,i){var
a=i;for(;;)if(typeof
a==="number")return 0;else
switch(a[0]){case
0:var
e=a[2],j=a[1];if(typeof
e==="number")switch(e){case
0:var
c=c5;break;case
1:var
c=c6;break;case
2:var
c=c7;break;case
3:var
c=c8;break;case
4:var
c=c9;break;case
5:var
c=c_;break;default:var
c=c$}else
switch(e[0]){case
0:var
c=e[1];break;case
1:var
c=e[1];break;default:var
c=br(da,F(ad(1,e[1])))}_(b,j);return at(b,c);case
1:var
g=a[2],h=a[1];if(0===g[0]){var
k=g[1];_(b,h);at(b,eP);var
a=k;continue}var
l=g[1];_(b,h);at(b,eQ);var
a=l;continue;case
6:var
p=a[2];_(b,a[1]);return at(b,d(p,0));case
7:var
a=a[1];continue;case
8:var
q=a[2];_(b,a[1]);return aH(q);case
2:case
4:var
n=a[2];_(b,a[1]);return at(b,n);default:var
o=a[2];_(b,a[1]);var
f=b[2];if(b[3]<=f)bu(b,1);m(b[1],f,o);b[2]=f+1|0;return 0}}var
bA=[0,0];function
bB(a){bA[1]=[0,a,bA[1]];return 0}var
bC=c,eS=bC.Object,eU=bC.Array,bD=[B,eV,aB(0)],aY=[0,bD,{}],eR=ft(aY)===B?aY:aY[1];fy(a(a3),eR);(function(a){throw a});bB(function(a){return a[1]===bD?[0,ac(a[2].toString())]:0});bB(function(a){return a
instanceof
eU?0:[0,ac(a.toString())]});var
bE={"wrapper":fn(function(f,b){var
c=ac(b),a=eW[1];return cF(d(e(function(d){var
e=64,b=as<64?as:e,c=u(b),a=[0,c,0,b,c];_(a,d);return bs(a[1],0,a[2])},0,a),c))})},eT=eS.keys(bE);eT.forEach(fm(function(a,d,c){var
b=bE[a];return fl(0)[a]=b}));function
cS(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{fp(d)}catch(a){a=fD(a);if(a[1]!==bq)throw a;var
e=a}var
a=c;continue}return 0}}cS(fr(0));return}(function(){return this}()));
